# Generated by Django 4.2.3 on 2023-07-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_user_picture_user_image_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
